// modules/auth/permissions.ts

export enum Permission {
  VIEW_DASHBOARD = 'VIEW_DASHBOARD',
  EDIT_USERS = 'EDIT_USERS',
  CREATE_USER = 'CREATE_USER',
  VIEW_USERS = 'VIEW_USERS',
  DELETE_USER = 'DELETE_USER',

  VIEW_STUDENTS = 'VIEW_STUDENTS',
  CREATE_STUDENT = 'CREATE_STUDENT',
  DELETE_STUDENT = 'DELETE_STUDENT',
  ASSIGN_STUDENTS = 'ASSIGN_STUDENTS',
  EDIT_STUDENT = 'EDIT_STUDENT',

  VIEW_CLASSES = 'VIEW_CLASSES',
  CREATE_CLASS = 'CREATE_CLASS',

  VIEW_ATTENDANCE = 'VIEW_ATTENDANCE',
  MARK_ATTENDANCE = 'MARK_ATTENDANCE',

  MANAGE_TEACHERS = 'MANAGE_TEACHERS',
  CREATE_TEACHER = 'CREATE_TEACHER',
  DELETE_TEACHER = 'DELETE_TEACHER',
  VIEW_TEACHERS = 'VIEW_TEACHERS',
  ASSIGN_TEACHER = 'ASSIGN_TEACHER',
  EDIT_TEACHER = 'EDIT_TEACHER',

  VIEW_REPORT_CARD = 'VIEW_REPORT_CARD',
  EDIT_REPORT_CARD = 'EDIT_REPORT_CARD',

  MANAGE_SETTINGS = 'MANAGE_SETTINGS',
}
